parameters:
#    zen_softdojo.example.class: ZenSoft\dojoBundle\Example

services:
#    zen_softdojo.example:
#        class: %zen_softdojo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
