ZenSoft\dojoBundle\Entity\Altas\Areas:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
        idEstablecimientos:
            type: integer
            column: id_establecimientos
    lifecycleCallbacks: {  }
